In [1]:
import pandas as pd
import utils
#cerrega todo os arquivos
dfNTLNew = pd.read_csv("./data/NTLHNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNTLNew.loc[dfNTLNew["versiculo"] >= "1" ]
dfNTLOld = pd.read_csv("./data/NTLHOld.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNTLOld.loc[dfNTLOld["versiculo"] >= "1" ]

dfARCNew = pd.read_csv("./data/ARCNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfARCNew.loc[dfARCNew["versiculo"] >= "1" ]
dfARCOld = pd.read_csv("./data/ARCOld.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfARCOld.loc[dfARCOld["versiculo"] >= "1" ]

dfNVIPTNew = pd.read_csv("./data/NVIPTNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNVIPTNew.loc[dfNVIPTNew["versiculo"] >= "1" ] 
dfNVIPTOld = pd.read_csv("./data/NVIPTOld.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNVIPTOld.loc[dfNVIPTOld["versiculo"] >= "1" ] 

dfNVTNew = pd.read_csv("./data/NVTNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNVTNew.loc[dfNVTNew["versiculo"] >= "1" ] 
dfNVTOld = pd.read_csv("./data/NVTOld.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfNVTOld.loc[dfNVTOld["versiculo"] >= "1" ] 

dfOLNew = pd.read_csv("./data/OLNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfOLNew.loc[dfOLNew["versiculo"] >= "1" ]
dfOLOld = pd.read_csv("./data/OLOld.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfOLOld.loc[dfOLOld["versiculo"] >= "1" ]

dfVFLNew = pd.read_csv("./data/VFLNew.tsv", sep="\t") # esse cara podemos fazer o seguinte filtro: dfVFLNew.loc[dfVFLNew["versiculo"] >= "1" ]

#eu posso fazer esses filtros ou remover tudo o que tenha o nome do livro por extenso e o nome do estilo. Se fizer isso presaremos reajustasr os indices

In [2]:
dfNTLNew

Unnamed: 0 estilo       livro  capitulo  versiculo  \
0              0   NTLH      Mateus         1          1   
1              1   NTLH      Mateus         1       2000   
2              2   NTLH      Mateus         1          2   
3              3   NTLH      Mateus         1          3   
4              4   NTLH      Mateus         1          4   
...          ...    ...         ...       ...        ...   
7892        7892   NTLH  Apocalipse        22         17   
7893        7893   NTLH  Apocalipse        22         18   
7894        7894   NTLH  Apocalipse        22         19   
7895        7895   NTLH  Apocalipse        22         20   
7896        7896   NTLH  Apocalipse        22         21   

                                                  texto  
0     Esta é a lista dos antepassados de Jesus Crist...  
1     Sociedade Bíblica do Brasil . Todos os direito...  
2     Abraão foi pai de Isaque , Isaque foi pai de J...  
3     Judá foi pai de Peres e de Zera , e a mãe dele...  
4     Arão foi pai de Aminadabe , que foi pai de Nas...  
...                                                 ...  
7892  O Espírito e a Noiva dizem : — Venha ! Aquele ...  
7893  Eu , João , aviso solenemente aos que ouvem as...  
7894  E , se alguma pessoa tirar alguma coisa das pa...  
7895  Aquele que dá testemunho de tudo isso diz : — ...  
7896  E que a graça do Senhor Jesus esteja com todos...  

[7897 rows x 6 columns]

In [3]:
#normalizando os nomes do novo testamento

print(set(dfNTLNew["livro"]) - set(dfARCNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfVFLNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfNVIPTNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfNVTNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfOLNew["livro"]))

dfNVIPTNew["livro"] = dfNVIPTNew["livro"].replace("Filemón", "Filemom")
dfNVTNew["livro"]   = dfNVTNew["livro"].replace("Filemón", "Filemom")
dfOLNew["livro"]    = dfOLNew["livro"].replace("Filemón", "Filemom")

print(set(dfNTLNew["livro"]) - set(dfARCNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfVFLNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfNVIPTNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfNVTNew["livro"]))
print(set(dfNTLNew["livro"]) - set(dfOLNew["livro"]))


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()


In [8]:
dictOldBooksNTLH = {"Gênesis": 50,
"Êxodo": 40,
"Levítico": 27,
"Números": 36,
"Deuteronômio": 34,
"Josué": 24,
"Juízes": 21,
"Rute": 4,
"1%20Samuel": 31,
"2%20Samuel": 24,
"1%20Reis": 22,
"2%20Reis": 25,
"1%20Crônicas": 29,
"2%20Crônicas": 36,
"Esdras": 10,
"Neemias": 13,
"Ester": 10,
"Jó": 42,
"Salmos": 150,
"Provérbios": 31,
"Eclesiastes": 12,
"Cântico%20dos%20Cânticos": 8,
"Isaías": 66,
"Jeremias": 52,
"Lamentações%20de%20Jeremias": 5,
"Ezequiel": 48,
"Daniel": 12,
"Oseias": 14,
"Joel": 3,
"Amós": 9,
"Obadias": 1,
"Jonas": 4,
"Miqueias": 7,
"Naum": 3,
"Habacuque": 3,
"Sofonias": 3,
"Ageu": 2,
"Zacarias":14,
"Malaquias": 4}

dfARCOld["livro"] = dfARCOld["livro"].replace("Cantares", "Cântico%20dos%20Cânticos")
dfARCOld["livro"] = dfARCOld["livro"].replace("Lamentações", "Lamentações%20de%20Jeremias")

dfNVIPTOld["livro"] = dfNVIPTOld["livro"].replace("Miquéias", "Miqueias")
dfNVIPTOld["livro"] = dfNVIPTOld["livro"].replace("Cantares%20de%20Salomâo", "Cântico%20dos%20Cânticos")

dfNVTOld["livro"] = dfNVTOld["livro"].replace("Miquéias", "Miqueias")
dfNVTOld["livro"] = dfNVTOld["livro"].replace("Cantares%20de%20Salomâo", "Cântico%20dos%20Cânticos")

dfOLOld["livro"] = dfOLOld["livro"].replace("Miquéias", "Miqueias")
dfOLOld["livro"] = dfOLOld["livro"].replace("Cantares%20de%20Salomâo", "Cântico%20dos%20Cânticos")


print(set(dfNTLOld["livro"]) - set(dfARCOld["livro"]))
print(set(dfNTLOld["livro"]) - set(dfNVIPTOld["livro"]))
print(set(dfNTLOld["livro"]) - set(dfNVTOld["livro"]))
print(set(dfNTLOld["livro"]) - set(dfOLOld["livro"]))





set()
set()
set()
set()


In [26]:

import numpy as np
#Matriz do velho testamento

#         dfNTLOld   dfARCOld   dfVFLOld  dfNVIPTOld   dfNVTOld  dfOLOld
#dfNTLOld
  
#dfARCOld

#dfVFLOld

#dfNVIPTOld

#dfNVTOld

#dfOLOld



[[    1 21691     1 22613 21684 22052]
 [    0     1     1 22657 22656 22021]
 [    0     0     1     1     1     1]
 [    0     0     0     1 22832 23030]
 [    0     0     0     0     1 22310]
 [    0     0     0     0     0     1]]


In [28]:

#Matriz do novo testamento

#         dfNTLNew   dfARCNew   dfVFLNew  dfNVIPTNew   dfNVTNew  dfOLNew
#dfNTLNew  

#dfARCNew

#dfVFLNew

#dfNVIPTNew

#dfNVTNew

#dfOLNew

[[   1 7638 7616 7896 7639 7835]
 [   1    1 7644 7686 7687 7627]
 [   1    1    1 7648 7651 7593]
 [   1    1    1    1 7690 7880]
 [   1    1    1    1    1 7634]
 [   1    1    1    1    1    1]]


In [10]:
dfNTLNew.to_csv("./data/NTLHNew.tsv", sep="\t")
dfNTLOld.to_csv("./data/NTLHOld.tsv", sep="\t")

dfARCNew.to_csv("./data/ARCNew.tsv", sep="\t")
dfARCOld.to_csv("./data/ARCOld.tsv", sep="\t")

dfNVIPTNew.to_csv("./data/NVIPTNew.tsv", sep="\t")
dfNVIPTOld.to_csv("./data/NVIPTOld.tsv", sep="\t")

dfNVTNew.to_csv("./data/NVTNew.tsv", sep="\t")
dfNVTOld.to_csv("./data/NVTOld.tsv", sep="\t")

dfOLNew.to_csv("./data/OLNew.tsv", sep="\t")
dfOLOld.to_csv("./data/OLOld.tsv", sep="\t")

dfVFLNew.to_csv("./data/VFLNew.tsv", sep="\t")

In [31]:
dfVFLNew.merge(dfARCNew, on=["livro", "capitulo", "versiculo"]).sample(5)

Unnamed: 0_x estilo_x          livro  capitulo  versiculo  \
7405          7660      VFL     Apocalipse         9         13   
2047          2100      VFL          Lucas         7         46   
4955          5094      VFL        Romanos        15         16   
5640          5807      VFL  2%20Coríntios        11         32   
3671          3768      VFL           João        21         12   

                                                texto_x  Unnamed: 0_y  \
7405  O sexto anjo tocou a sua trombeta e eu ouvi um...          7693   
2047  Você não derramou óleo sobre a minha cabeça . ...          2100   
4955  o privilégio de ser ministro de Jesus Cristo ,...          5106   
5640  Quando estive em Damasco , o governador que se...          5825   
3671  Jesus lhes disse : —Venham comer . ( Nenhum do...          3771   

     estilo_y                                            texto_y  
7405      ARC  E tocou o sexto anjo a trombeta , e ouvi uma v...  
2047      ARC  Não me ungiste a cabeça com óleo , mas esta un...  
4955      ARC  que eu seja ministro de Jesus Cristo entre os ...  
5640      ARC  Em Damasco , o que governava sob o rei Aretas ...  
3671      ARC  Disse-lhes Jesus : Vinde , jantai . E nenhum d...

In [32]:
dfOLOld.merge(dfNVTOld, on=["livro", "capitulo", "versiculo"]).sample(5)

Unnamed: 0_x estilo_x     livro  capitulo  versiculo  \
3854           4069       OL   Números        12         16   
14869         15865       OL    Salmos        97         11   
14426         15396       OL    Salmos        73         26   
4196           4424       OL   Números        23         30   
20530         21809       OL  Ezequiel        33          3   

                                                 texto_x  Unnamed: 0_y  \
3854   Partindo dali , de Hazerote , vieram a acampar...          4234   
14869  A luz é feita para os retos e a alegria para o...         16196   
14426  A minha saúde e o meu espírito enfraquecem , m...         15729   
4196   Balaque fez conforme essa indicação e ofereceu...          4607   
20530  quando este vir chegar as tropas inimigas e de...         22164   

      estilo_y                                            texto_y  
3854       NVT  Então saíram de Hazerote e acamparam no desert...  
14869      NVT  A luz brilha sobre os justos , e a alegria , s...  
14426      NVT  Minha saúde pode acabar e meu espírito fraquej...  
4196       NVT  Balaque seguiu as instruções de Balaão e ofere...  
20530      NVT  Quando o vigia vê o inimigo , ele dá o sinal d...

In [49]:
import numpy as np

def getTriOverlap(source, target):
    try:
        return source, target
    except:
        return 0.0
    

def getStats(dfA, dfB):
    df = dfA.merge(dfB, on=["livro", "capitulo", "versiculo"])

    df["sourceLen"] = df["texto_x"].apply(lambda x: getSizeSentece(x))
    df["targetLen"] = df["texto_y"].apply(lambda x: getSizeSentece(x))
    
    df["BLEU"] = df.apply(lambda x: getBleu(x["texto_x"], x["texto_y"]), axis=1)

    return df.shape[0], df.shape[0], df["sourceLen"].sum(), df["targetLen"].sum(), df["sourceLen"].mean(), df["targetLen"].mean(), df["BLEU"].mean()
#Matriz do novo testamento

def getSizeSentece(text):
    try:
        return len(text.split(" "))
    except:
        return 0
    
def getBleu(source, target):
    try:
        return sentence_bleu([source.split(" ")], target.split(" "), weights=(1, 0, 0, 0))
    except:
        return 0.0

print("Novo testamento: ")
print("NTLNew-VFLNew       : ", getStats(dfNTLNew, dfVFLNew))
print("NTLNew-dfNVIPTNew   : ", getStats(dfNTLNew, dfNVIPTNew))
print("NTLNew-dfNVTNew     : ", getStats(dfNTLNew, dfNVTNew))
print("NTLNew-dfOLNew      : ", getStats(dfNTLNew, dfOLNew))
print("dfARCNew-dfVFLNew   : ", getStats(dfARCNew, dfVFLNew))
print("dfARCNew-dfNVIPTNew : ", getStats(dfARCNew, dfNVIPTNew))
print("dfARCNew-dfNVTNew   : ", getStats(dfARCNew, dfNVTNew))
print("dfARCNew-dfOLNew    : ", getStats(dfARCNew, dfOLNew))
print("dfVFLNew-ARCNew     : ", getStats(dfVFLNew, dfNVIPTNew))
print("dfVFLNew-ARCNew     : ", getStats(dfVFLNew, dfNVTNew))
print("dfVFLNew-ARCNew     : ", getStats(dfVFLNew, dfOLNew))
print("dfNVIPTNew-dfNVTNew : ", getStats(dfNVIPTNew, dfNVTNew))
print("dfNVIPTNew-dfOLNew  : ", getStats(dfNVIPTNew, dfOLNew))
print("dfNVTNew-dfOLNew    : ", getStats(dfNVTNew, dfOLNew))
print("Velho testamento: ")
print("dfNTLOld-dfARCOld    : ", getStats(dfNTLOld, dfARCOld))
print("dfNTLOld-dfNVIPTOld    : ", getStats(dfNTLOld, dfNVIPTOld))
print("dfNTLOld-dfNVTOld    : ", getStats(dfNTLOld, dfNVTOld))
print("dfNTLOld-dfOLOld    : ", getStats(dfNTLOld, dfOLOld))
print("dfARCOld-dfNVIPTOld    : ", getStats(dfARCOld, dfNVIPTOld))
print("dfARCOld-dfNVTOld    : ", getStats(dfARCOld, dfNVTOld))
print("dfARCOld-dfOLOld    : ", getStats(dfARCOld, dfOLOld))
print("dfNVIPTOld-dfNVTOld    : ", getStats(dfNVIPTOld, dfNVTOld))
print("dfNVIPTOld-dfOLOld    : ", getStats(dfNVIPTOld, dfOLOld))
print("dfNVTOld-dfOLOld    : ", getStats(dfNVTOld, dfOLOld))

#TODO


# métricas de similaridade do córpus final (sacre-BLEU)



Novo testamento: 


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

NTLNew-VFLNew       :  (7616, 7616, 216028, 228171, 28.36502100840336, 29.959427521008404, 0.5344695215763303)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

NTLNew-dfNVIPTNew   :  (7896, 7896, 220289, 196777, 27.898809523809526, 24.92109929078014, 0.46612609653839127)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

NTLNew-dfNVTNew     :  (7639, 7639, 216699, 203209, 28.367456473360388, 26.601518523366934, 0.4620016314028549)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

NTLNew-dfOLNew      :  (7835, 7835, 218803, 205398, 27.92635609444799, 26.215443522654756, 0.3884459442835739)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCNew-dfVFLNew   :  (7644, 7644, 186652, 229117, 24.41810570381999, 29.973443223443223, 0.4201069084215655)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCNew-dfNVIPTNew :  (7686, 7686, 187623, 194621, 24.411007025761123, 25.321493624772312, 0.5158761698684662)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCNew-dfNVTNew   :  (7687, 7687, 187645, 204531, 24.410693378431116, 26.60738909847795, 0.4161165393524054)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCNew-dfOLNew    :  (7627, 7627, 186364, 203304, 24.434771207552117, 26.65582797954635, 0.40470183574128105)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfVFLNew-ARCNew     :  (7648, 7648, 229363, 193660, 29.9899320083682, 25.321652719665273, 0.4845498924502986)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfVFLNew-ARCNew     :  (7651, 7651, 229557, 203560, 30.00352895046399, 26.605672461116193, 0.46174621869186816)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfVFLNew-ARCNew     :  (7593, 7593, 227734, 202404, 29.992624785987093, 26.65665744764915, 0.3872944579651463)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVIPTNew-dfNVTNew :  (7690, 7690, 194783, 204574, 25.329388816644993, 26.60260078023407, 0.5471878096138777)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVIPTNew-dfOLNew  :  (7880, 7880, 196590, 206585, 24.94796954314721, 26.216370558375633, 0.45157872224524825)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVTNew-dfOLNew    :  (7634, 7634, 203306, 203405, 26.631647891013884, 26.6446161907257, 0.4451488160687411)
Velho testamento: 


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNTLOld-dfARCOld    :  (21691, 21691, 635502, 618649, 29.297957678299756, 28.52099949287723, 0.36625067389481036)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNTLOld-dfNVIPTOld    :  (22613, 22613, 648368, 608551, 28.672356609030203, 26.911555300048644, 0.41979449852217077)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNTLOld-dfNVTOld    :  (21684, 21684, 635335, 604515, 29.29971407489393, 27.878389596015495, 0.41615741797116745)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNTLOld-dfOLOld    :  (22052, 22052, 633606, 582794, 28.732359876655178, 26.428169780518775, 0.3264010744319446)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCOld-dfNVIPTOld    :  (22657, 22657, 640266, 615714, 28.259081078695328, 27.1754424681114, 0.46004519159420526)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCOld-dfNVTOld    :  (22656, 22656, 640232, 622923, 28.25882768361582, 27.494835805084747, 0.39169027571282145)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfARCOld-dfOLOld    :  (22021, 22021, 622124, 585555, 28.25139639435085, 26.59075428000545, 0.3406540869446259)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVIPTOld-dfNVTOld    :  (22832, 22832, 616770, 624500, 27.013402242466714, 27.35196215837421, 0.5160804435738243)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVIPTOld-dfOLOld    :  (23030, 23030, 611119, 597486, 26.535779418150238, 25.943812418584454, 0.3809825266000908)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

dfNVTOld-dfOLOld    :  (22310, 22310, 609238, 588536, 27.30784401613626, 26.37991931869117, 0.3818572556545304)


c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\Users\pablo\anaconda3\envs\torch\Lib\site-packages\nltk\translate\bleu_score.py:552: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or

NTLNew-VFLNew       :  (7616, 7616, 216028, 228171, 28.36502100840336, 29.959427521008404, 0.5344695215763303)
